name: Fetch News Data  # 뉴스 데이터 수집

on:
  schedule:
    - cron: '*/20 * * * *'  # 20분마다 실행 (UTC 기준)
  workflow_dispatch:  # 수동 실행 가능하게 추가 (옵션)
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest  # 최신 Ubuntu 환경에서 실행

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 리포지토리 체크아웃
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 푸시 권한 추가

      - name: Set up Python
        uses: actions/setup-python@v4  # Python 환경 설정
        with:
          python-version: '3.9'  # 원하는 Python 버전 설정
    
      - name: package install
        run: |
          pip install requests
          pip install beautifulsoup4
          pip install numpy==1.21.2  
          pip install gensim==3.8.3  
          pip install flask  # flask 패키지 설치
          pip install selenium  # selenium 패키지 설치
          pip install scipy==1.7.3  # scipy 버전 1.7.3으로 고정
          
      - name: change push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-action@github.com"
    
          git add *.db  # .db 파일이 있을 경우에만 추가
          git commit -m "Update news data (auto)"         
          git push
